#!/bin/bash
# PWA Offline Setup & Test Guide

echo "🔧 PWA Offline Implementation - Setup Steps"
echo "==========================================="
echo ""

echo "Step 1: Install dependencies"
echo "Run: npm install -D vite-plugin-pwa workbox-build"
echo ""

echo "Step 2: Build the project"
echo "Run: npm run build"
echo "Expected output:"
echo "  ✓ Service Worker generated with all chunk hashes"
echo "  ✓ Workbox manifest created"
echo "  ✓ build completes without errors"
echo ""

echo "Step 3: Preview build locally"
echo "Run: npm run preview"
echo "Browser opens at: http://localhost:4173"
echo ""

echo "Step 4: Test Offline (Critical)"
echo "==========================================="
echo ""
echo "Option A: DevTools Offline Mode (Recommended)"
echo "  1. Open DevTools (F12)"
echo "  2. Go to Network tab"
echo "  3. Check 'Offline' checkbox"
echo "  4. Refresh page (Cmd+R)"
echo "  5. Verify:"
echo "     ✓ App loads fully (no blank screen)"
echo "     ✓ Daily page shows habits, prayers, tracking"
echo "     ✓ Indicator shows: 'Offline • Changes saved locally'"
echo "     ✓ Can make edits (they save to localStorage)"
echo ""

echo "Option B: Network Throttling"
echo "  1. DevTools Network tab → throttling preset"
echo "  2. Select 'Slow 3G' or 'Offline'"
echo "  3. Refresh page"
echo "  4. Should load without ChunkLoadError"
echo ""

echo "Step 5: Test Reconnect"
echo "  1. Go back online (uncheck Offline or set throttle to 'No throttling')"
echo "  2. Verify:"
echo "     ✓ Indicator shows: 'Back online • Changes will sync'"
echo "     ✓ Indicator hides after 2 seconds"
echo "     ✓ App fetches fresh data from Supabase"
echo ""

echo "Step 6: Test Specific Pages Offline"
echo "  1. Go offline again"
echo "  2. Test each route:"
echo "     ✓ / (Daily) - should show all data"
echo "     ✓ /quran - should show reading progress"
echo "     ✓ /duas - should load duas without error"
echo "     ✓ /fasting - should show qadha tracker"
echo "     ✓ /cycle - should show period logs"
echo "     ✓ /report - should show analytics"
echo ""

echo "Step 7: Verify Cache in DevTools"
echo "  1. DevTools → Application → Cache Storage"
echo "  2. Should see:"
echo "     ✓ amaly-XXXXXX (auto-generated version)"
echo "     ✓ quran-cdn (Quran external CDN)"
echo "     ✓ duas-data (Duas component data)"
echo "     ✓ supabase-api (API responses)"
echo ""

echo "Troubleshooting"
echo "==========================================="
echo ""
echo "Issue: App fails to load offline"
echo "  → Check browser console (F12 → Console)"
echo "  → Look for ChunkLoadError"
echo "  → Verify Service Worker registered: Application → Service Workers"
echo "  → Try hard refresh: Cmd+Shift+R (Mac) or Ctrl+Shift+R (Windows)"
echo ""

echo "Issue: Indicator doesn't show"
echo "  → Check OfflineIndicator component loads (inspect bottom-left)"
echo "  → Verify App.tsx has <OfflineIndicator /> after <BottomNav />"
echo "  → Check browser console for import errors"
echo ""

echo "Issue: Quran data not cached"
echo "  → Make sure app loaded once online first"
echo "  → Quran CDN caches on first load, then available offline"
echo "  → Verify cache in DevTools → quran-cdn store"
echo ""

echo "Issue: Changes not saving offline"
echo "  → localStorage should still work offline"
echo "  → Check DevTools → Application → Local Storage"
echo "  → Verify app-store.ts is updating localStorage keys"
echo ""

echo "Success! PWA offline is ready."
echo "Now discuss sync queue strategy for later phase."
